name: Build Image

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Zip Archive
        run: |
          zip -r webapp.zip ./

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.Project_Id }}

      - name: Set up Packer
        run: |
            wget https://releases.hashicorp.com/packer/1.7.3/packer_1.7.3_linux_amd64.zip
            unzip packer_1.7.3_linux_amd64.zip
            chmod +x packer
            sudo mv packer /usr/local/bin/
            cd Packer
            echo '${{ secrets.GCP_SA_KEY }}' > credentials.json
            packer init
        shell: bash

      - name: Run Packer fmt
        run: |
          cd Packer
          packer fmt -check packerconfig.json.pkr.hcl
        continue-on-error: true

      - name: Run Packer validate
        run: |
          cd Packer
          packer validate packerconfig.json.pkr.hcl

      - name: Run Packer build
        run: |
          cd Packer
          packer build packerconfig.json.pkr.hcl
